name: "Deploy frontend"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - "!frontend/README.md"

jobs:
  build-and-deploy:
    name: "Build and deploy frontend"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run test --if-present

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.SA_EMAIL }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Set target hosting site
        run: |
          cat <<'EOF' > .firebaserc
          {
            "projects": {},
            "targets": {
              "default": {
                "hosting": [
                  ["${{ vars.FIREBASE_HOSTING_SITE_ID }}"]
                ]
              }
            },
            "etags": {}
          }
          EOF

      - name: Deploy hosting site
        run: npx firebase deploy --only hosting --project "${{ vars.GCP_PROJECT_ID }}"
